

# Print tar contents:
# 1: Interpreted as relative to the root directory
# 2: With no trailing slashes on directories
# This is useful for ensuring that the output matches the
# values generated by the "find" command
ls_tar() {
  for f in $(tar -tf $1 | xargs realpath -ms --relative-to=.); do
    if [[ "$f" != "." ]]; then
      echo "/$f"
    fi
  done
}
